# Generated by Django 4.2.1 on 2023-05-08 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_board', '0004_post_datecreation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='liked',
        ),
    ]
