# Generated by Django 4.2.1 on 2023-05-10 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_board', '0005_remove_post_liked'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(height_field=100, null=True, upload_to='article', width_field=100),
        ),
    ]
